# Generated by Django 4.0.4 on 2022-05-16 12:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('HP', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('WIL', models.IntegerField()),
                ('armor', models.IntegerField(blank=True)),
                ('attack1', models.CharField(blank=True, max_length=60)),
                ('attack2', models.CharField(blank=True, max_length=60)),
                ('crit', models.TextField(blank=True)),
                ('special', models.TextField(blank=True)),
                ('spells', models.CharField(blank=True, max_length=60)),
                ('wants', models.TextField(blank=True)),
                ('variation_name', models.CharField(blank=True, max_length=60)),
                ('variation_text', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
    ]
