# Generated by Django 4.0.4 on 2022-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='variation_text',
            field=models.TextField(blank=True),
        ),
    ]
