# Generated by Django 4.0.4 on 2022-05-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0003_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='variation_text',
        ),
    ]
